# Simplified Nixpacks configuration for Railway deployment
[variables]
NODE_ENV = "production"

# Install phase - use standard npm install
[phases.install]
cmds = ["npm ci"]

# Build phase - generate Prisma client  
[phases.build]
cmds = ["npx prisma generate"]

# Start phase - run the application
[phases.start]
cmd = "npm start"
