# Nixpacks configuration for Railway deployment
[variables]
NODE_ENV = "production"

# Install phase - install all dependencies first
[phases.install]
cmds = ["npm ci"]

# Build phase - generate Prisma client after install
[phases.build]
cmds = ["npx prisma generate"]

# Start phase - run migrations then start the application
[phases.start]
cmd = "npx prisma migrate deploy && npm start"
