# Nixpacks configuration for Railway deployment
[variables]
NODE_ENV = "production"
OPENSSL_CONF = "/dev/null"
PRISMA_CLI_BINARY_TARGETS = "native,debian-openssl-1.1.x,linux-musl"

# Setup phase - install system dependencies including OpenSSL 1.1
[phases.setup]
nixPkgs = ["nodejs-18_x", "openssl_1_1"]

# Install phase - install all dependencies first
[phases.install]
cmds = ["npm ci"]

# Build phase - generate Prisma client with correct binary targets
[phases.build]
cmds = ["npx prisma generate"]

# Start phase - run migrations then start the application
[phases.start]
cmd = "npx prisma migrate deploy && npm start"
