#!/bin/bash

echo "🌐 Railway Domain Generation Guide"
echo "================================="
echo ""
echo "1. Go to Railway Dashboard"
echo "2. Click on your BACKEND service (not database)"
echo "3. Go to Settings tab"
echo "4. Find 'Public Networking' section"
echo "5. Click 'Generate Domain'"
echo "6. Copy the generated URL"
echo ""
echo "Your URL will look like:"
echo "https://[random-name].up.railway.app"
echo ""
echo "Then run: ./test-railway-deployment.sh"
echo "And paste your Railway URL when prompted"
echo ""
echo "🚨 IMPORTANT: Make sure you generate domain for:"
echo "   ✅ Backend SERVICE (your Node.js app)"
echo "   ❌ NOT the PostgreSQL database"
